import "@ui5/webcomponents-base/dist/features/OpenUI5Support.js";

import "@ui5/webcomponents/dist/Avatar.js";
import "@ui5/webcomponents/dist/AvatarGroup.js";
//import "@ui5/webcomponents/dist/Badge.js";
import "@ui5/webcomponents/dist/Breadcrumbs.js";
import "@ui5/webcomponents/dist/BreadcrumbsItem.js";
import "@ui5/webcomponents/dist/Bar.js";
import "@ui5/webcomponents/dist/Button.js";
import "@ui5/webcomponents/dist/Calendar.js";
import "@ui5/webcomponents/dist/Card.js";
import "@ui5/webcomponents/dist/Carousel.js";
import "@ui5/webcomponents/dist/CheckBox.js";
import "@ui5/webcomponents/dist/ComboBox.js";
import "@ui5/webcomponents/dist/DatePicker.js";
import "@ui5/webcomponents/dist/DateRangePicker.js";
import "@ui5/webcomponents/dist/DateTimePicker.js";
import "@ui5/webcomponents/dist/Dialog.js";
import "@ui5/webcomponents-fiori/dist/DynamicPage.js";
import "@ui5/webcomponents-fiori/dist/DynamicPageHeader.js";
import "@ui5/webcomponents-fiori/dist/DynamicPageTitle.js";
import "@ui5/webcomponents/dist/Form.js";
import "@ui5/webcomponents/dist/FormGroup.js";
import "@ui5/webcomponents/dist/FormItem.js";
import "@ui5/webcomponents/dist/Icon.js";
import "@ui5/webcomponents/dist/Label.js";
import "@ui5/webcomponents/dist/MessageStrip.js";
import "@ui5/webcomponents/dist/Input.js";
import "@ui5/webcomponents/dist/Link.js";
import "@ui5/webcomponents/dist/List.js";
//import "@ui5/webcomponents/dist/StandardListItem.js";
//import "@ui5/webcomponents/dist/CustomListItem.js";
//import "@ui5/webcomponents/dist/GroupHeaderListItem.js";
import "@ui5/webcomponents/dist/Panel.js";
import "@ui5/webcomponents-fiori/dist/ProductSwitch.js";
import "@ui5/webcomponents-fiori/dist/ProductSwitchItem.js";
import "@ui5/webcomponents-fiori/dist/ShellBar.js";
import "@ui5/webcomponents-fiori/dist/ShellBarItem.js";
import "@ui5/webcomponents/dist/StepInput.js";
import "@ui5/webcomponents/dist/TabContainer.js";
import "@ui5/webcomponents/dist/Tab.js";
import "@ui5/webcomponents/dist/TabSeparator.js";
//import "@ui5/webcomponents/dist/Table.js";
//import "@ui5/webcomponents/dist/TableColumn.js";
//import "@ui5/webcomponents/dist/TableRow.js";
//import "@ui5/webcomponents/dist/TableCell.js";
import "@ui5/webcomponents/dist/TextArea.js";
import "@ui5/webcomponents-fiori/dist/Timeline.js";
import "@ui5/webcomponents/dist/TimePicker.js";
import "@ui5/webcomponents/dist/Title.js";
import "@ui5/webcomponents-fiori/dist/Wizard.js";
import "@ui5/webcomponents-fiori/dist/Page.js";

import "./icons.js"

import "@ui5/webcomponents/dist/Assets.js";
import "@ui5/webcomponents-fiori/dist/Assets.js";

//import { setTheme } from "@ui5/webcomponents-base/dist/config/Theme.js";
//setTheme("sap_fiori_3");
